//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace RuleAdministration.Interfaces
{
	public interface IAction
	{
		/// <summary>
		/// Determines whether this instance is applicable the specified obj.
		/// </summary>
		/// <returns><c>true</c> if this instance is appli-
		/// cable the specified obj; otherwise, <c>false</c>.</returns>
		/// <param name="obj">Object.</param>
		bool IsApplicable(params GameObject[]  list);

		/// <summary>
		/// Processes the action. In this function concret 
		/// action consequences are handled, e.g. Create or 
		/// destroy the given GameObject  
		/// </summary>
		/// <returns><c>true</c>, if action was processed, <c>false</c> otherwise.</returns>
		/// <param name="obj">Object.</param>
		bool Update(params GameObject[] list);

		/// <summary>
		/// Do some action state changes. E.g. if a action have to do some calculations.
		/// Otherwise create a empty method;
		/// </summary>
		void BeforeUpdate(params GameObject[] list);

		/// <summary>
		/// Name of the action.
		/// </summary>
		string Name();
		
	}
}

