//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using RuleAdministration.Interfaces;


namespace RuleAdministration.Rules
{
		public class BrainCoralRule : IRule
		{
			#region constructors

			public BrainCoralRule ()
			{
			}

			#endregion

			#region IRule implementation
			
			/// <summary>
			/// Determines whether this instance is applicable.
			/// </summary>
			/// <returns><c>true</c> if this instance is applicable; otherwise, <c>false</c>.</returns>
			public bool IsApplicable (/*coral type*/)
			{
				// if(coral type == brain coral) return true;
				// return false;
				throw new NotImplementedException ();
			}
			
			/// <summary>
			/// Corals the is placeable.
			/// </summary>
			/// <returns><c>true</c>, if is placeable was coraled, <c>false</c> otherwise.</returns>
			public bool CoralIsPlaceable (/* board cell */)
			{
				// if (board cell.neighbors contains at least 3 leaf corals) return true;
				// return false;
				throw new NotImplementedException ();
			}

			#endregion
		}
}

