//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using RuleAdministration.Interfaces;
using UnityEngine;
using System.Collections.Generic;
using RuleAdministration.Administrators;


namespace RuleAdministration.Rules
{
	public class RemoveAction : IAction
	{
		#region constructors
		
		public RemoveAction ()
		{
			
		}
		
		#endregion
		
		
		
		/// <summary>
		/// Determines whether this instance is applicable.
		/// </summary>
		/// <returns><c>true</c> if this instance is applicable; otherwise, <c>false</c>.</returns>
		public bool IsApplicable (GameObject obj)
		{
			Common obj_common = obj.GetComponent<Common> ();
			if (obj_common == null) { 
				Debug.LogError ("The passed object is not placable. It doesn't contain a Common behaviour.");
				return false;
			}
			return true;
		}
		
		
		public string Name ()
		{
			return "RemoveAction";
		}
		
		
		public bool ProcessAction (GameObject obj)
		{
			GameObject.Destroy(obj);
			return false;
		}
		
		
	}
}

