// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

 public interface IAppearenceChangable
 {
 	/// <summary>
 	/// Changes the appearance.
 	/// </summary>
 	/// <param name="target">Target.</param>
  	void ChangeType(string target);
  	
	/// <summary>
	/// Gets or sets the mashes.
	/// </summary>
	/// <value>The mashes.</value>
	Dictionary<string, UnityEngine.Mesh> _MeshDict{set;get;}
 }

