//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using RuleAdministration.Interfaces;
using UnityEngine;
using System.Collections.Generic;
using RuleAdministration.Administrators;
using System.Collections;
	
namespace RuleAdministration.Rules
{
	public class SADowngrade : IAction
	{
			
		private SAExpand m_expand;
		
		public SADowngrade ()
		{
		}
		
		 
		public Common CurrentObject{get;set;}	
		public void SetObject(Common obj)
		{
			CurrentObject = obj;
			m_expand = new SAExpand();
			m_expand.SetObject(CurrentObject);
		}
		
		public bool IsApplicable ()
		{
			return m_expand.IsApplicable();
		}
			
		public string Name ()
		{
			return "Downgrade";
		}
			
		public void Update ()
		{
			
			ActionAdministrator.Instance.ApplyAction (m_expand, CurrentObject);
						
		}

		public void BeforeUpdate ()
		{
			
			string new_type = "Boden";
			// Get previouse 
			switch (CurrentObject.FigureType) {
			case "C":
				new_type = "B";
				break;
			case "B":
				new_type = "A";
				break;
			case "A":
				new_type = "Boden";
				break;
			}
			m_expand.SetTypeName (new_type);
		}
			
		
		
	}
}

