// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using RuleAdministration.Interfaces;
using System.Runtime.CompilerServices;
using UnityEngine.Internal;

namespace RuleAdministration.Rules
{
	public class SARandomTransform : IAction
	{
  
		public override string Name ()
		{
			return "RandomTransformationAction";
		}
			
		public override void Update ()
		{
			Transform[] transformable = _Tile.gameObject.GetComponents <Transform> ();
			for (int i = 0; i < transformable.Length; i++) {
				
				//SCALE	
				float r = UnityEngine.Random.Range (0.90f, 1.1f);
				transformable [i].localScale = new Vector3 (
					 r * transformable [i].localScale.x,
					 r * transformable [i].localScale.y,
					 r * transformable [i].localScale.z);
				
				//POSITION
				if (transformable [i].gameObject.name == "pal_B" || transformable [i].gameObject.name == "pal_C") {
					r = UnityEngine.Random.Range (-0.1f, 0.1f);
					transformable [i].localPosition = new Vector3 (
						 r + transformable [i].localPosition.x,
						 r + transformable [i].localPosition.y,
						 transformable [i].localPosition.z);
				}
				
				//ROTATION
				transformable [i].localRotation = Quaternion.Euler (
					transformable [i].localRotation.x,
					UnityEngine.Random.Range (0.0f, 360.0f) + transformable [i].localRotation.y,
					transformable [i].localRotation.z);
				
				//SET BACK ROTATION OF "BODEN"
				if (transformable [i].gameObject.name == "Boden" || transformable [i].gameObject.name == "Particle System")
					transformable [i].localRotation = Quaternion.identity;
			}
		}
	}
}

