// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using RuleAdministration.Interfaces;
using System.Runtime.CompilerServices;
using UnityEngine.Internal;

namespace RuleAdministration.Rules
{
	public class SAScale : IAction
	{
		public float _ScaleFactor;
  
		public override string Name ()
		{
			return "SAScale";
		}
			
		public override void Update ()
		{
				//SCALE	
				_Tile._Pal._Appearence.transform.localScale = new Vector3 (
				_ScaleFactor,
				_ScaleFactor,
				_ScaleFactor);
		
		}
	}
}
	


