//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using RuleAdministration.Interfaces;
using UnityEngine;
using System.Collections.Generic;
using RuleAdministration.Administrators;
using System.Collections;
	
namespace RuleAdministration.Rules
{
	public class SAUpgrade : IAction
	{
		private SAExpand expand;
		
		public SAUpgrade ()
		{
			
		}
		
		public Common CurrentObject{get;set;}
		
		public void SetObject (Common obj)
		{
			CurrentObject = obj;
			expand = new SAExpand();
			expand.SetObject(CurrentObject);
		}
		
		public bool IsApplicable ()
		{
			return expand.IsApplicable();
		}
			
		public string Name ()
		{
			return "Upgrade";
		}
			
		public void Update ()
		{
			string new_type = "C";
			
			// Get next gen. object type
			switch(CurrentObject.FigureType)
			{
			case "Boden" : new_type = "A"; break;
			case "A" : new_type = "B"; break;
			case "B" : new_type = "C"; break;
			}
			
			// Reuse ExpandAction for placing object
			
			expand.SetTypeName(new_type);
			ActionAdministrator.Instance.ApplyAction(expand,CurrentObject);
						
		}

		public void BeforeUpdate ()
		{
		}
			
		
		
	}
}

