//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using RuleAdministration.Interfaces;
using UnityEngine;
using System.Collections.Generic;
using RuleAdministration.Administrators;
using System.Collections;
	
namespace RuleAdministration.Rules
{
	public class GlobalRandomSelectionAction : IRandomAction
	{
		
		public GlobalRandomSelectionAction (){}
		
		public Common CurrentObject{get;set;}
		public IAction SingleAction{get;set;}
		public int MaximalNumberOfObjects{get; set;}
		
			
		public Common[] GetRandomObjects (System.Random random)
		{
			Common[] result;
			int n = random.Next (1, MaximalNumberOfObjects);
			result = new Common[n];
			
			for (int i = 0; i < n; i++) {
				result [i] = 
				worldXSingelton.WorldObjects [
				random.Next (worldXSingelton.WorldObjects.GetLength (0)),
				random.Next (worldXSingelton.WorldObjects.GetLength (1))
				];
			}
			return result;		
		}
		
		public bool IsApplicable ()
		{
			return true;
		}
			
		public string Name ()
		{
			return "Random Access Action";
		}
			
		public void Update ()
		{
			ActionAdministrator.Instance.ApplyAction (this.SingleAction, CurrentObject);		
		}

		public void BeforeUpdate ()
		{
			
		}
			
		
		
	}
}

