//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using RuleAdministration.Interfaces;
using UnityEngine;
using System.Collections.Generic;
using RuleAdministration.Administrators;
using System.Collections;
using System.Linq;
	
namespace RuleAdministration.Rules
{
	public class LocalRandomSelector : ISelector
	{
		private Tile m_Tile;
		public int Radius{get;set;}

		public Tile _Tile {
			get {
				return m_Tile;
			}
			set {
				m_Tile = value;
			}
		}
		
		public LocalRandomSelector (Vector2 currentPos, int radius)
		{
			this.Radius = radius;
//			this._Tile = new Tile(currentPos.x,currentPos.y);	
			
		}
		
		
		
		public LocalRandomSelector (Tile locator, int radius)
		{
			this.Radius = radius;
			this._Tile = locator;	
		}
		
			
		public Tile[] GetSelectedObjects ()
		{
			System.Random random = new System.Random();
			
			int n = random.Next (1, (2*Radius+1)^2);
			
			Vector2 origin = this.m_Tile._Position;
			
			HashSet<Vector2> result_pos = new HashSet<Vector2>();
			List<Tile> result = new List<Tile>();
			for (int i = 0; i < n;) {
				Vector2 pos = new Vector2(
					random.Next (((int)origin.x - Radius) < 0 ? 0 : (int)origin.x - Radius,
				             ((int)origin.x + Radius) >= Paradise.Intance._TileObjects.GetLength(0) ? Paradise.Intance._TileObjects.GetLength(0) - 1: ((int)origin.x + Radius)),
					random.Next (((int)origin.y - Radius) < 0 ? 0 : (int)origin.y - Radius,
				             ((int)origin.x + Radius) >= Paradise.Intance._TileObjects.GetLength(1) ? Paradise.Intance._TileObjects.GetLength(1) - 1: ((int)origin.y + Radius))
				               );
				
				
				if(pos == this._Tile._Position) continue;
				if(result_pos.Contains(pos)) continue;
				
				result_pos.Add(pos);
				result.Add(Paradise.Intance._TileObjects[(int)pos.x,(int)pos.y]);
				
				i++; 
				}
			
			return result.ToArray();		
		}
	}
}

