//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace RuleAdministration.Interfaces
{
	public interface IAction
	{
		bool IsApplicable(GameObject ob);

		bool ProcessAction(GameObject ob);

		string Name();
		
	}
}

