//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace RuleAdministration.Interfaces
{
	    /// <summary>
	    /// I rule administrator.
	    /// </summary>
		public interface IRuleAdministrator
		{
			void ApplyAction<T>(GameObject obj) where T:new();
			void ApplyAction(GameObject obj, IAction action);

			void ApplyActionGlobal<T>() where T:new();
			void ApplyActionGlobal(IAction action);

			void RegisterRule(string type, /*string category,*/ IAction rule);
		}
}

